version: '3.2'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.3
    environment:
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
  zetcd:
    image: quay.io/coreos/zetcd:v0.0.4
    command: --zkaddr 0.0.0.0:2181 --endpoints etcd:2379
    ports:
      - "2181:2181"
    depends_on:
      - 'etcd'
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - 'zetcd'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zetcd:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_PROTOCOL_NAME: INTERNAL
      KAFKA_HOST_NAME: kafka
      KAFKA_MESSAGE_MAX_BYTES: 26214400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 26214400
      KAFKA_CREATE_TOPICS: testuser.api_tokens:1:1,testuser.uploaded:1:1,testuser.jobs:1:1,testuser.pipelines:1:1,testuser.processed:1:1,operators:1:1
  object-store:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: accessKey1
      MINIO_SECRET_KEY: verySecretKey1
  api:
    image: dev.digitalernachschub.de/ameto/api
    depends_on:
      - 'kafka'
      - 'object-store'
    environment:
      - AMETO_KAFKA_BROKERS=kafka:9092
      - AMETO_API_BIND_ADDRESS=0.0.0.0
      - AMETO_ADVERTISED_URL=http://delivery:80
      - AMETO_OBJECT_STORE=object-store:9000
      - AMETO_OBJECT_STORE_ACCESS_KEY=accessKey1
      - AMETO_OBJECT_STORE_SECRET_KEY=verySecretKey1
      - AMETO_OBJECT_STORE_USE_TLS=false
  dispatcher:
    image: dev.digitalernachschub.de/ameto/dispatcher
    depends_on:
      - 'kafka'
      - 'object-store'
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
    environment:
      - AMETO_KAFKA_BROKERS=kafka:9092
      - AMETO_OPERATORS_EVENT_STORE_PATH=/var/lib/ameto/dispatcher/events
      - AMETO_OBJECT_STORE=object-store:9000
      - AMETO_OBJECT_STORE_ACCESS_KEY=accessKey1
      - AMETO_OBJECT_STORE_SECRET_KEY=verySecretKey1
      - AMETO_OBJECT_STORE_USE_TLS=false
  exporter:
    image: dev.digitalernachschub.de/ameto/exporter
    depends_on:
      - 'kafka'
    volumes:
      - type: volume
        source: ameto_exporter
        target: /var/lib/ameto/exporter
    environment:
      - AMETO_KAFKA_BROKERS=kafka:9092
      - AMETO_EXPORTER_DIR=/var/lib/ameto/exporter
      - AMETO_OBJECT_STORE=object-store:9000
      - AMETO_OBJECT_STORE_ACCESS_KEY=accessKey1
      - AMETO_OBJECT_STORE_SECRET_KEY=verySecretKey1
      - AMETO_OBJECT_STORE_USE_TLS=false
  delivery:
    image: nginx
    depends_on:
      - 'api'
      - 'object-store'
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

volumes:
  ameto_exporter:
