version: '3.2'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.3
    environment:
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
  zetcd:
    image: quay.io/coreos/zetcd:v0.0.4
    command: --zkaddr 0.0.0.0:2181 --endpoints etcd:2379
    ports:
      - "2181:2181"
    depends_on:
      - 'etcd'
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - 'zetcd'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zetcd:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_PROTOCOL_NAME: INTERNAL
      KAFKA_HOST_NAME: kafka
      KAFKA_MESSAGE_MAX_BYTES: 262144000
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 262144000
      KAFKA_CREATE_TOPICS: testUser.api_tokens:1:1,testUser.uploaded:1:1,testUser.jobs:1:1,testUser.pipelines:1:1,testUser.processed:1:1,operators:1:1
  api:
    image: dev.digitalernachschub.de/ameto/api
    depends_on:
      - 'kafka'
    environment:
      - AMETO_KAFKA_BROKERS=kafka:9092
      - AMETO_API_BIND_ADDRESS=0.0.0.0
      - AMETO_DELIVERY_URL=http://delivery:80/
  dispatcher:
    image: dev.digitalernachschub.de/ameto/dispatcher
    depends_on:
      - 'kafka'
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
    environment:
      - AMETO_KAFKA_BROKERS=kafka:9092
      - AMETO_OPERATORS_EVENT_STORE_PATH=/var/lib/ameto/dispatcher/events
  exporter:
    image: dev.digitalernachschub.de/ameto/exporter
    depends_on:
      - 'kafka'
    volumes:
      - type: volume
        source: ameto_exporter
        target: /var/lib/ameto/exporter
    environment:
      - AMETO_KAFKA_BROKERS=kafka:9092
      - AMETO_EXPORTER_DIR=/var/lib/ameto/exporter
  delivery:
    image: nginx
    volumes:
      - type: volume
        source: ameto_exporter
        target: /usr/share/nginx/html
        read_only: true

volumes:
  ameto_exporter:
