FROM gradle:4.4-jdk-alpine as gradle
COPY settings.gradle settings.gradle
COPY build.gradle build.gradle
COPY src src
COPY .git .git

CMD ["gradle", "--no-daemon", "--full-stacktrace", "integrationTest"]
