version: '3.2'
services:
  zookeeper:
    image: digitalwonderland/zookeeper
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - 'zookeeper'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CREATE_TOPICS: assets:1:1,ameto-assets-changelog:1:1,jobs:1:1,ameto-jobs-changelog:1:1,operators:1:1,ameto-operators-changelog:1:1,pipelines:1:1,ameto-pipelines-changelog:1:1,tenants:1:1,ameto-tenants-changelog:1:1,users:1:1,ameto-users-changelog:1:1
  object-store:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: accessKey1
      MINIO_SECRET_KEY: verySecretKey1
  api:
    image: dev.digitalernachschub.de/ameto/api:2.0.0
    depends_on:
      - 'kafka'
      - 'object-store'
    environment:
      - AMETO_KAFKA_BROKERS=kafka:9092
      - AMETO_API_BIND_ADDRESS=0.0.0.0
      - AMETO_ADVERTISED_URL=http://delivery:80
      - AMETO_OBJECT_STORE=object-store:9000
      - AMETO_OBJECT_STORE_ACCESS_KEY=accessKey1
      - AMETO_OBJECT_STORE_SECRET_KEY=verySecretKey1
      - AMETO_OBJECT_STORE_USE_TLS=false
      - AMETO_API_MAX_CONSISTENCY_LAG=1000
      - AMETO_API_ADMIN_USER=admin
      - AMETO_API_ADMIN_USER_PASSWORD=V4l1dAdm1nT0ken
      - AMETO_API_SECRET_KEY=abcd1234
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
  proxy:
    image: envoyproxy/envoy-alpine
    depends_on:
      - "api"
    volumes:
      - "./envoy.yml:/etc/envoy/envoy.yaml:ro"
  delivery:
    image: nginx
    depends_on:
      - 'proxy'
      - 'object-store'
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
