version: '3.2'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.3
    environment:
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
  zetcd:
    image: quay.io/coreos/zetcd:v0.0.4
    command: --zkaddr 0.0.0.0:2181 --endpoints etcd:2379
    ports:
      - "2181:2181"
    depends_on:
      - 'etcd'
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - 'zetcd'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zetcd:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: EXTERNAL
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INTERNAL
      KAFKA_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: api_tokens:1:1,assets:1:1,jobs:1:1,operators:1:1,pipelines:1:1,processed:1:1
    ports:
      - "9094:9094"
  object-store:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: accessKey1
      MINIO_SECRET_KEY: verySecretKey1
    ports:
      - "9000:9000"
  api:
    image: dev.digitalernachschub.de/ameto/api
    depends_on:
      - 'kafka'
      - 'object-store'
    ports:
      - "9100:5000"
    environment:
      - AMETO_KAFKA_BROKERS=kafka:9092
      - AMETO_API_BIND_ADDRESS=0.0.0.0
      - AMETO_ADVERTISED_URL=http://localhost:9200
      - AMETO_OBJECT_STORE=object-store:9000
      - AMETO_OBJECT_STORE_ACCESS_KEY=accessKey1
      - AMETO_OBJECT_STORE_SECRET_KEY=verySecretKey1
      - AMETO_OBJECT_STORE_USE_TLS=false
      - AMETO_API_USER_TOPIC_PARTITIONS=1
      - AMETO_API_USER_TOPIC_REPLICATION_FACTOR=1
      - AMETO_API_MAX_CONSISTENCY_LAG=1000
      - AMETO_API_ADMIN_USER=admin
      - AMETO_API_ADMIN_USER_TOKEN=V4l1dAdm1nT0ken
  dispatcher:
    image: dev.digitalernachschub.de/ameto/dispatcher
    depends_on:
      - 'kafka'
      - 'object-store'
    ports:
      - "9110:8080"
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
    environment:
      - AMETO_KAFKA_BROKERS=kafka:9092
      - AMETO_OPERATORS_EVENT_STORE_PATH=/var/lib/ameto/dispatcher/events
      - AMETO_OBJECT_STORE=object-store:9000
      - AMETO_OBJECT_STORE_ACCESS_KEY=accessKey1
      - AMETO_OBJECT_STORE_SECRET_KEY=verySecretKey1
      - AMETO_OBJECT_STORE_USE_TLS=false
      - AMETO_DISPATCHER_MAX_CONSISTENCY_LAG=1000
  delivery:
    image: nginx
    depends_on:
      - 'api'
      - 'object-store'
    ports:
      - "9200:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
